server:
  port: 8081
spring:
  cloud:
    config:
      server:
        git:
          default-label: config-sercer
          uri: https://github.com/chancrex/microservicios-prueba
          search-paths: config-data
  application:
    name: config-sercer 